name: ajeeb
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  flutter_swiper: ^1.1.6
  provider: ^4.0.4
  flutter_spinkit: ^4.1.2
  email_validator: '^1.0.0'
  fluttertoast: ^4.0.1
  image_picker: ^0.6.4
  shimmer: ^1.1.1
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_datetime_picker: ^1.3.8
  url_launcher: ^5.4.5
  flutter_search_panel: ^1.0.1
  shared_preferences:
  carousel_slider: ^1.3.0
  after_layout: ^1.0.7+2
  flutter_rating_bar: ^1.1.0
  smooth_star_rating: 1.0.3


  cached_network_image: ^2.2.0
  firebase_storage:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  file_picker: ^1.1.1
  intl: ^0.15.7
  transparent_image: ^1.0.0
  firebase_database:
  web_socket_channel: ^1.1.0

flutter_icons:
  image_path: "assets/appIcon.jpg"
  android: true
  ios: true



flutter_launcher_name:
  name: "Penta Events"
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/appIcon.jpg
    - assets/strings.jpg
    - assets/stars.jpg
    - assets/noimg.jpg
    - assets/bg.jpg
    - assets/bgimg2.jpg
    - assets/bgimg3.jpg
    - assets/bgimg4.jpg
    - assets/bgimg5.jpg
    - assets/background.jpg
    - assets/des.jpg
    - assets/des2.jpg
    - assets/des3.jpg
    - assets/des4.jpg
    - assets/bgimg6.jpg
    - assets/bgimg7.jpg
    - assets/bgimg8.jpg
    - assets/bgimg9.jpg
    - assets/cust.jpg
    - assets/eventmanager.jpg
    - assets/bgimg.jpg
    - assets/logo1.jpg
    - assets/logo2.jpg
    - assets/logo3.png
    - assets/logo4.jpg
    - assets/logo5.jpg
    - assets/logo6.jpg
    - assets/logo7.jpg
    - assets/logo8.jpg
    - assets/logo9.png
    - assets/logo10.jpg
    - assets/logo11.png
    - assets/logo12.jpg
    - assets/logo13.png
    - assets/logo14.jpg
    - assets/cover1.jpg
    - assets/cover2.jpg
    - assets/cover3.jpg
    - assets/cover4.jpg
    - assets/cover5.jpg
    - assets/cover6.jpg
    - assets/cover7.jpg
    - assets/cover8.jpg
    - assets/cover9.jpg
    - assets/cover10.jpg
    - assets/cover11.jpg
    - assets/cover12.jpg
    - assets/cover13.jpg
    - assets/cover14.jpg
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/p3.jpg
    - assets/p4.jpg
    - assets/p5.jpg
    - assets/pkg1.jpg
    - assets/backgorund1.jpg
    - assets/backgorund2.jpg
    - assets/backgorund3.jpg
    - assets/backgorund4.jpg
    - assets/backgorund5.jpg
    - assets/backgorund6.jpg
    - assets/backgorund7.jpg
    - assets/backgorund8.jpg
    - assets/backgorund9.jpg
    - assets/backgorund10.jpg
    - assets/backgorund11.jpg
    - assets/backgorund12.jpg
    - assets/background15.jpg
    - assets/c1.jpg
    - assets/c2.jpg
    - assets/c3.jpg
    - assets/c4.jpg
    - assets/c5.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
